export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_BULLET_MAX_COUNT = 10;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_Y_OFFSET = -20;
export const PLAYER_BULLET_SPEED = 500;
export const PLAYER_BULLET_LIFESPAN = 3;
export const PLAYER_HEALTH = 4;
export const PLAYER_LIVES = 3;

export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 4;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 3000;
export const ENEMY_FIGHTER_BULLET_Y_OFFSET = 10;
export const ENEMY_FIGHTER_BULLET_SPEED = -300;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
export const ENEMY_FIGHTER_HEALTH = 1;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 6000;
export const ENEMY_FIGHTER_GROUP_SPAWN_START = 3000;
export const ENEMY_FIGHTER_SCORE = 200;

export const ENEMY_FRIGATE_MOVEMENT_VERTICAL_VELOCITY = 1;
export const ENEMY_FRIGATE_BULLET_MAX_COUNT = 10;
export const ENEMY_FRIGATE_BULLET_INTERVAL = 1500;
export const ENEMY_FRIGATE_BULLET_Y_OFFSET = 25;
export const ENEMY_FRIGATE_BULLET_SPEED = -300;
export const ENEMY_FRIGATE_BULLET_LIFESPAN = 3;
export const ENEMY_FRIGATE_MOVEMENT_MAX_X = 60;
export const ENEMY_FRIGATE_MOVEMENT_HORIZONTAL_VELOCITY = 3;
export const ENEMY_FRIGATE_HEALTH = 3;
export const ENEMY_FRIGATE_GROUP_SPAWN_INTERVAL = 10000;
export const ENEMY_FRIGATE_GROUP_SPAWN_START = 5000;
export const ENEMY_FRIGATE_SCORE = 400;

export const ENEMY_BATTLECRUISER_MOVEMENT_VERTICAL_VELOCITY = 0.25;
export const ENEMY_BATTLECRUISER_BULLET_MAX_COUNT = 10;
export const ENEMY_BATTLECRUISER_BULLET_INTERVAL = 750;
export const ENEMY_BATTLECRUISER_BULLET_Y_OFFSET = 55;
export const ENEMY_BATTLECRUISER_BULLET_SPEED = -500;
export const ENEMY_BATTLECRUISER_BULLET_LIFESPAN = 3;
export const ENEMY_BATTLECRUISER_MOVEMENT_MAX_X = 100;
export const ENEMY_BATTLECRUISER_MOVEMENT_HORIZONTAL_VELOCITY = 5;
export const ENEMY_BATTLECRUISER_HEALTH = 8;
export const ENEMY_BATTLECRUISER_GROUP_SPAWN_INTERVAL = 60000;
export const ENEMY_BATTLECRUISER_GROUP_SPAWN_START = 60000;
export const ENEMY_BATTLECRUISER_SCORE = 800;

export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 40;
export const ENEMY_SCOUT_HEALTH = 1;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 2000;
export const ENEMY_SCOUT_GROUP_SPAWN_START = 1000;
export const ENEMY_SCOUT_SCORE = 100;

export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;

export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
